### ISSUE TITLE
add delay to 100ms to 200ms send socket, if possible

### ISSUE THREAD

**Issue by JJAshcraft** [Lambda-School-Labs/Labs8-TeamComms#142]
future feature as user grow, create a false input box the user typing sees so it is
responsive on a local level, overlayed over the server data. with a delay to update everyone else in the meeting, so fast typing looks good

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tlinehan** [comment]
Austin improved.  May need future improvement at a later time.
